# -*- coding: utf-8 -*-
"""1_test_pilot_phd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_Cq8xGwr_KGM40mnTVv3qi-JPBmjDwU
"""

try:
    from docx import Document
except ImportError:
    import subprocess
    import sys
    print("Instalando biblioteca 'python-docx'...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "python-docx"])
    from docx import Document

import re
import pandas as pd

def clean_text(text):
    """
    Remove as marcas de Jefferson para criar a versão higienizada.
    """
    # Remove pausas (.), (..), (3s)
    text = re.sub(r'\(\.*\d*s?\)', '', text)
    # Remove alongamentos vocálicos ::
    text = re.sub(r'::', '', text)
    # Remove pausas preenchidas comuns
    hesitacoes = ['ééé', 'ahn', 'hum', 'mm', 'uh', 'eh']
    for h in hesitacoes:
        text = re.sub(rf'\b{h}\b', '', text, flags=re.IGNORECASE)
    # Remove espaços duplos resultantes da limpeza
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def calculate_human_score(text):
    """
    Calcula a nota de 0 a 100 baseada na densidade de marcas (heurística).
    """
    score = 100
    # Penalidades conforme nossa tabela técnica
    score -= len(re.findall(r'ééé|ahn|hum|mm', text, re.I)) * 5
    score -= len(re.findall(r'::', text)) * 5
    score -= len(re.findall(r'\(\.\)', text)) * 5
    score -= len(re.findall(r'\(\.\.\)', text)) * 10
    score -= len(re.findall(r'\b[a-zA-Z]+-', text)) * 10 # Truncamentos

    return max(0, score)

def convert_docx_to_csv(docx_path, csv_output):
    doc = Document(docx_path)
    data = []
    current_id = 1

    for para in doc.paragraphs:
        line = para.text.strip()
        if not line:
            continue

        # Tenta separar Nome: Fala usando Regex
        match = re.match(r'^([^:]+):\s*(.*)', line)

        if match:
            locutor = match.group(1).strip()
            fala_fiel = match.group(2).strip()

            fala_higienizada = clean_text(fala_fiel)
            nota_humana = calculate_human_score(fala_fiel)

            data.append({
                "ID": f"{current_id:02d}",
                "LOCUTOR": locutor,
                "FALA_FIEL": fala_fiel,
                "FALA_HIGIENIZADA": fala_higienizada,
                "NOTA_HUMANA": nota_humana
            })
            current_id += 1

    # Criar DataFrame e exportar
    df = pd.DataFrame(data)
    df.to_csv(csv_output, index=False, encoding='utf-8-sig')
    print(f"Sucesso! Arquivo '{csv_output}' gerado com {len(df)} linhas.")
    return df

# --- EXECUÇÃO NO COLAB ---
# O caminho do arquivo deve ser uma string (entre aspas)
nome_do_arquivo_word = "/content/Entrevista Galvão Bueno.docx"

try:
    df_resultado = convert_docx_to_csv(nome_do_arquivo_word, "pilot_benchmark.csv")
    # Mostrar as primeiras linhas para conferência
    if not df_resultado.empty:
        print("\nVisualização dos primeiros dados gerados:")
        print(df_resultado.head())
except Exception as e:
    print(f"Erro: Certifique-se de que subiu o arquivo no caminho correto. Detalhes: {e}")