# -*- coding: utf-8 -*-
"""2_JuntarCSV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10f_Q68j9oltVDxG_Zfk5EjgqlYpTfDII
"""

import pandas as pd
import os

def consolidar_benchmarks(arquivos_config, output_name="pilot_benchmark_consolidado.csv"):
    """
    Junta múltiplos CSVs em um único dataset estruturado para análise de ECE.

    arquivos_config: Lista de dicionários contendo 'path' e 'nome_entrevista'.
    """
    datasets = []

    print("Iniciando consolidação dos arquivos...")

    for config in arquivos_config:
        path = config['path']
        # A função precisa que a chave seja exatamente 'nome_entrevista'
        nome_entrevista = config['nome_entrevista']

        if os.path.exists(path):
            # Carrega o CSV individual
            df_temp = pd.read_csv(path)

            # Adiciona/Sobrescreve a coluna de metadados da entrevista
            df_temp['ENTREVISTA'] = nome_entrevista

            # Garante que as colunas essenciais existam (validação de esquema)
            colunas_obrigatorias = ['LOCUTOR', 'FALA_FIEL', 'FALA_HIGIENIZADA', 'NOTA_HUMANA']
            for col in colunas_obrigatorias:
                if col not in df_temp.columns:
                    print(f"Aviso: Coluna '{col}' não encontrada em {path}!")

            datasets.append(df_temp)
            print(f"✔ {nome_entrevista} carregada: {len(df_temp)} linhas.")
        else:
            print(f"❌ Erro: Arquivo {path} não encontrado.")

    if not datasets:
        print("Nenhum dado foi carregado. Verifique os caminhos dos arquivos.")
        return

    # Concatena todos os dataframes
    df_final = pd.concat(datasets, ignore_index=True)

    # Reinicia a coluna ID para garantir uma sequência única global (1 até N)
    df_final['ID'] = range(1, len(df_final) + 1)

    # Reorganiza as colunas conforme a estrutura_dataset_triplo.md
    ordem_colunas = ['ID', 'ENTREVISTA', 'LOCUTOR', 'FALA_FIEL', 'FALA_HIGIENIZADA', 'NOTA_HUMANA']
    # Mantém outras colunas caso existam, mas coloca as principais no início
    outras_cols = [c for c in df_final.columns if c not in ordem_colunas]
    df_final = df_final[ordem_colunas + outras_cols]

    # Salva o arquivo final
    df_final.to_csv(output_name, index=False)
    print(f"\n✅ Sucesso! Dataset consolidado salvo como: {output_name}")
    print(f"Total final de amostras: {len(df_final)}")

    return df_final

# --- CONFIGURAÇÃO DOS SEUS ARQUIVOS ---
# IMPORTANTE: Mantenha a chave 'nome_entrevista' para que a função funcione
meus_arquivos = [
    {'path': '/content/pilot_benchmark_marco.csv', 'nome_entrevista': 'Marco Aurelio'},
    {'path': '/content/pilot_benchmark_galvao.csv', 'nome_entrevista': 'Galvao_Bueno'},
    {'path': '/content/pilot_benchmark.csv', 'nome_entrevista': 'Heloisa_Starling'}
]

# Execução
if __name__ == "__main__":
    df_resultado = consolidar_benchmarks(meus_arquivos)

    # Exibe as primeiras linhas para conferência
    if df_resultado is not None:
        display(df_resultado.head())