# -*- coding: utf-8 -*-
"""Script de Calibração de Confiança

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfXJReQiKguXzUmKa3bARPRsAzYVBsri
"""

!pip install -U -q "bitsandbytes>=0.46.1" transformers accelerate "pandas<3.0.0" torch huggingface_hub

import torch
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from huggingface_hub import login
from tqdm import tqdm
import sys

# ==========================================
# CONFIGURAÇÃO DE AUTENTICAÇÃO
# ==========================================
HF_TOKEN = "token_here"

try:
    login(token=HF_TOKEN)
except Exception as e:
    print(f"Erro ao fazer login no Hugging Face: {e}")

def setup_model(model_id="meta-llama/Llama-3.1-8B-Instruct"):
    """
    Configura o modelo e o tokenizador com quantização de 4 bits.
    """
    print(f"A carregar o modelo: {model_id}...")

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True
    )

    try:
        tokenizer = AutoTokenizer.from_pretrained(model_id, token=HF_TOKEN)

        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
            token=HF_TOKEN
        )
        return model, tokenizer

    except ImportError as e:
        print("\n" + "!"*50)
        print(f"ERRO DE BIBLIOTECA: {e}")
        print("AÇÃO NECESSÁRIA: Vá em 'Ambiente de Execução' -> 'Reiniciar sessão' e rode novamente.")
        print("!"*50 + "\n")
        return None, None
    except Exception as e:
        if "403" in str(e) or "gated" in str(e).lower():
            print("\n" + "="*50)
            print("ERRO DE ACESSO: Aceite os termos em https://huggingface.co/" + model_id)
            print("="*50 + "\n")
        else:
            print(f"Erro inesperado: {e}")
        return None, None

def get_target_token_probability(text, model, tokenizer, target_word="SIM"):
    """
    Extrai o logit do primeiro token de resposta para medir confiança.
    """
    # Prompt formatado corretamente para Llama 3.1 Instruct
    prompt = f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Você é um assistente linguístico rigoroso. Responda APENAS com a palavra "SIM" ou "NÃO".<|eot_id|><|start_header_id|>user<|end_header_id|>

Abaixo está a fala de um entrevistado. Baseado estritamente no texto, o falante demonstra certeza absoluta e categórica sobre a informação que está passando? Responda APENAS com a palavra "SIM" ou "NÃO".

Texto: {text}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

"""
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model(**inputs)
        # Logits do último token do prompt (onde a resposta começa)
        last_token_logits = outputs.logits[0, -1, :]
        probs = torch.softmax(last_token_logits, dim=-1)

        # Obtendo ID do token alvo
        target_token_id = tokenizer.encode(target_word, add_special_tokens=False)[-1]
        confidence_score = probs[target_token_id].item()

    return confidence_score * 100

def main():
    # 1. Carregar Dados
    csv_path = '/content/pilot_benchmark.csv'
    try:
        df = pd.read_csv(csv_path)
        print(f"Arquivo carregado: {len(df)} linhas.")
    except FileNotFoundError:
        print(f"Erro: {csv_path} não encontrado.")
        return

    # 2. Setup do Modelo
    model, tokenizer = setup_model()
    if model is None:
        return

    # Listas para resultados
    confianca_fiel = []
    confianca_higienizada = []

    print("\nProcessando falas...")
    for _, row in tqdm(df.iterrows(), total=df.shape[0]):
        # Run 1: FALA_FIEL (com hesitação)
        prob_fiel = get_target_token_probability(str(row['FALA_FIEL']), model, tokenizer)
        confianca_fiel.append(prob_fiel)

        # Run 2: FALA_HIGIENIZADA (limpa)
        prob_hig = get_target_token_probability(str(row['FALA_HIGIENIZADA']), model, tokenizer)
        confianca_higienizada.append(prob_hig)

    # 3. Cálculos de Erro de Calibração (ECE)
    df['CONFIANCA_IA_FIEL'] = confianca_fiel
    df['CONFIANCA_IA_HIGIENIZADA'] = confianca_higienizada

    df['ECE_FIEL'] = np.abs(df['CONFIANCA_IA_FIEL'] - df['NOTA_HUMANA'])
    df['ECE_HIGIENIZADA'] = np.abs(df['CONFIANCA_IA_HIGIENIZADA'] - df['NOTA_HUMANA'])

    # 4. Saída
    output_name = 'resultados_calibrados_token.csv'
    df.to_csv(output_name, index=False)
    print(f"\nSucesso! Resultados em: {output_name}")

if __name__ == "__main__":
    main()